# Generated by Django 2.2.9 on 2020-01-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
