# Generated by Django 2.2.9 on 2020-01-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200121_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='passwd',
            field=models.CharField(max_length=300),
        ),
    ]
